WORKDIR /root

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
  ca-certificates \
  nano \
  wget \
  curl \
  gnupg \
  ripgrep \
  ltrace \
  file\
  python3-minimal \
  build-essential \
  git \
  cmake \
  ninja-build
ENV PATH="${PATH}:/opt/rocm/bin:/opt/rocm/llvm/bin:/usr/local/cuda/bin/"


ARG CUDA_VERSION=11-8
ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES compute,utility
RUN wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.0-1_all.deb
RUN dpkg -i cuda-keyring_1.0-1_all.deb && \
  apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
  nvidia-headless-no-dkms-515 \
  nvidia-utils-515 \
  cuda-cudart-${CUDA_VERSION} \
  cuda-compiler-${CUDA_VERSION} \
  libcufft-dev-${CUDA_VERSION} \
  libcusparse-dev-${CUDA_VERSION} \
  libcublas-dev-${CUDA_VERSION} \
  cuda-nvml-dev-${CUDA_VERSION} \
  libcudnn8-dev \
  cuda-toolkit-${CUDA_VERSION}

ARG RUST_VERSION=1.66.1
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain=${RUST_VERSION} && \
   . $HOME/.cargo/env && \
   cargo install bindgen-cli --locked
   

ARG ROCM_VERSION=5.7.3
RUN echo "Package: *\nPin: release o=repo.radeon.com\nPin-Priority: 600" > /etc/apt/preferences.d/rocm-pin-600
RUN mkdir --parents --mode=0755 /etc/apt/keyrings && \
  sh -c 'wget https://repo.radeon.com/rocm/rocm.gpg.key -O - |  gpg --dearmor | tee /etc/apt/keyrings/rocm.gpg > /dev/null' && \
  sh -c 'echo deb [arch=amd64 signed-by=/etc/apt/keyrings/rocm.gpg] https://repo.radeon.com/rocm/apt/${ROCM_VERSION} jammy main > /etc/apt/sources.list.d/rocm.list' && \
  apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
  rocminfo \
  rocm-gdb \
  rocprofiler \
  rocm-smi-lib \
  hip-runtime-amd \
  comgr \
  hipblaslt-dev \
  hipfft-dev \
  rocblas-dev \
  rocsolver-dev \
  rocsparse-dev \
  miopen-hip-dev \
  rocm-device-libs && \
  echo 'export PATH="$PATH:/opt/rocm/bin"' > /etc/profile.d/rocm.sh && \
  echo '/opt/rocm/lib' > /etc/ld.so.conf.d/rocm.conf && \
  ldconfig



# Install Zluda
RUN git clone --recurse-submodules https://github.com/vosen/ZLUDA.git $HOME/ZLUDA && \
    cd $HOME/ZLUDA && \
    $HOME/.cargo/bin/cargo xtask --release


# Install Miniconda
RUN sh -c "wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh" && \
    chmod +x Miniconda3-latest-Linux-x86_64.sh && \
    sh Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/miniconda3 && \
    echo 'export PATH="$HOME/miniconda3"' >> $HOME/.bashrc && \
    . $HOME/miniconda3/etc/profile.d/conda.sh && \
    . $HOME/.bashrc && \
    conda --version 

RUN apt-get install -y python3-pip && \
    pip --version
   

# Install PyTorch
RUN git clone --recursive https://github.com/pytorch/pytorch $HOME/pytorch && \
    cd $HOME/pytorch && \
    git submodule sync && \
    git submodule update --init --recursive
    
RUN cd $HOME/pytorch && \
    . $HOME/miniconda3/etc/profile.d/conda.sh && \
    . $HOME/.bashrc && \ 
    conda install -y cmake ninja

RUN cd $HOME/pytorch && \
    pip install -r requirements.txt && \
    pip install ninja && \
    export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"} && \
    export TORCH_CUDA_ARCH_LIST="6.1+PTX" && \
    export CUDAARCHS=61 && \
    export CMAKE_CUDA_ARCHITECTURES=61 && \
    export USE_SYSTEM_NCCL=1 && \
    export USE_NCCL=0 && \
    export USE_EXPERIMENTAL_CUDNN_V8_API=OFF && \
    export DISABLE_ADDMM_CUDA_LT=1 && \
    export USE_ROCM=0                      
#    LD_LIBRARY_PATH="$HOME/ZLUDA/target/release:$LD_LIBRARY_PATH" python3 setup.py develop

#cleanup
RUN rm cuda-keyring_1.0-1_all.deb Miniconda3-latest-Linux-x86_64.sh && \
    apt-get autoclean -y && \
    apt-get autoremove -y

# Default to a login shell
CMD ["bash", "-l"]
